### ISSUE TITLE
"Cannot POST /account/create" when trying to sign up for an account.

### ISSUE THREAD

**Issue by 0wG** [lightbulblighter/Rboxlo#86] opened 2021-06-14 02:18 UTC
I was told to make another issue for this so I did.
![image](https://user-images.githubusercontent.com/80175409/121831074-6dcb0f00-cc7b-11eb-852f-46e6fe7c8470.png)
Also, lets say I want to update something in the .env file. Would i just run `docker compose up --build` again?

**Comment by lightbulblighter** [comment] 2021-06-14 02:25
To answer the updating question, yes; that is the correct way to do that. I'll try to address the account registration issue ASAP because as of right now I do not have the ability to even reproduce the issue.

**Comment by lightbulblighter** [comment] 2021-06-14 05:20
I couldn't reproduce this issue. Can you try using a more updated version of Rboxlo? Preferably a version after commit 3dad3cf.

**Comment by 0wG** [comment] 2021-06-14 23:32
Im using 6c2c32a3.
![image](https://user-images.githubusercontent.com/80175409/121971009-07a2c280-cd35-11eb-8723-a196184eae95.png)
Also, when trying to register on http://rboxlo.loc/account/register gets me this as an error, even though I finished the captcha.
![image](https://user-images.githubusercontent.com/80175409/121971034-12f5ee00-cd35-11eb-80b2-5278c20e6ac9.png)
Sorry for another dumb question, but is there another way to add an account without registering on the website?

**Comment by lightbulblighter** [comment] 2021-06-15 00:11
It seems that the issue has resolved itself? You managed to receive a POST request on `/account/create` because your screenshot shows the website giving back an error message. I assume the issue can be closed now?

>  Also, when trying to register on http://rboxlo.loc/account/register gets me this as an error, even though I finished the captcha.
Fixed as of 1aeed70.

> is there another way to add an account without registering on the website?
There is a way, though it is very difficult and tedious. You'd have to hookup a client to the database container (either external client or shell) and simulate the website registering an account. The account registration code is in `user::createAccount` with the main account creation code [here.](https://github.com/lightbulblighter/Rboxlo/blob/trunk/Server/websites/eclipse/lib/user.js#L724) I wouldn't recommend doing this, though.

**Comment by lightbulblighter** [comment] 2021-06-15 17:48
I'm going to close this because as of e791d66 account registration works perfectly, unless you encounter another issue. It seems your issue is caused by having an older version of Rboxlo.

**Closed by lightbulblighter** 2021-06-15 17:48 UTC
Labels: Can't Reproduce, Need Info
